name: 知らせて.jp
permalink: /news/:year/:month/:title
relative_permalinks: false

paginate: 5
paginate_path: "news/page/:num"

# Prose settings
prose:
  rooturl: '_posts'
  siteurl: "http://info.shirasete.georepublic.net"
  relativeLinks: 'http://info.shirasete.georepublic.net/links.jsonp'
  media: "media"

